# Generated by Django 5.2.6 on 2025-10-05 11:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('director_dashboard', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CulturalReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='عنوان التقرير')),
                ('report_type', models.CharField(max_length=50, verbose_name='نوع التقرير')),
                ('content', models.TextField(verbose_name='المحتوى')),
                ('file', models.FileField(blank=True, null=True, upload_to='cultural_reports/%Y/%m/', verbose_name='ملف مرفق')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('committee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cultural_reports', to='director_dashboard.committee')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'تقرير ثقافي',
                'verbose_name_plural': 'التقارير الثقافية',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CulturalTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task_type', models.CharField(choices=[('cultural_data', 'بيانات ومسابقات ثقافية'), ('weekly_program', 'البرنامج الثقافي الأسبوعي'), ('reading_followup', 'متابعة القراءة النافعة'), ('friday_lesson', 'دروس لقاء دوري (عصر الجمعة)'), ('courses_coordination', 'تنسيق الدورات الهادفة')], max_length=50, verbose_name='نوع المهمة')),
                ('title', models.CharField(max_length=255, verbose_name='العنوان')),
                ('description', models.TextField(verbose_name='الوصف')),
                ('status', models.CharField(choices=[('pending', 'قيد التنفيذ'), ('in_progress', 'جاري العمل'), ('completed', 'مكتملة'), ('cancelled', 'ملغاة')], default='pending', max_length=20, verbose_name='الحالة')),
                ('due_date', models.DateField(verbose_name='تاريخ الاستحقاق')),
                ('completion_percentage', models.IntegerField(default=0, verbose_name='نسبة الإنجاز')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assigned_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cultural_tasks_assigned', to=settings.AUTH_USER_MODEL, verbose_name='المسؤول')),
                ('committee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cultural_tasks', to='director_dashboard.committee')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cultural_tasks_created', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'مهمة ثقافية',
                'verbose_name_plural': 'المهام الثقافية',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Discussion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='العنوان')),
                ('content', models.TextField(verbose_name='المحتوى')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_pinned', models.BooleanField(default=False, verbose_name='مثبت')),
                ('committee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='discussions', to='director_dashboard.committee')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='discussions_created', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'نقاش',
                'verbose_name_plural': 'التعليقات والنقاشات',
                'ordering': ['-is_pinned', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='DiscussionComment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(verbose_name='التعليق')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('discussion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='cultural_committee_dashboard.discussion')),
            ],
            options={
                'verbose_name': 'تعليق',
                'verbose_name_plural': 'التعليقات',
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='FileLibrary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_type', models.CharField(choices=[('cultural_plan', 'خطة ثقافية'), ('competition', 'مسابقة'), ('book_summary', 'ملخص كتاب'), ('other', 'أخرى')], max_length=50, verbose_name='نوع الملف')),
                ('title', models.CharField(max_length=255, verbose_name='العنوان')),
                ('description', models.TextField(blank=True, verbose_name='الوصف')),
                ('file', models.FileField(upload_to='cultural_files/%Y/%m/', verbose_name='الملف')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('committee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cultural_files', to='director_dashboard.committee')),
                ('uploaded_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'ملف ثقافي',
                'verbose_name_plural': 'مكتبة الملفات',
                'ordering': ['-uploaded_at'],
            },
        ),
        migrations.CreateModel(
            name='CulturalNotification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notification_type', models.CharField(choices=[('task_added', 'إضافة مهمة'), ('task_updated', 'تعديل مهمة'), ('file_uploaded', 'رفع ملف'), ('report_uploaded', 'رفع تقرير'), ('discussion_created', 'نقاش جديد')], max_length=50)),
                ('title', models.CharField(max_length=255)),
                ('message', models.TextField()),
                ('is_read', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('committee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='director_dashboard.committee')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cultural_notifications', to=settings.AUTH_USER_MODEL)),
                ('related_report', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='cultural_committee_dashboard.culturalreport')),
                ('related_task', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='cultural_committee_dashboard.culturaltask')),
                ('related_file', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='cultural_committee_dashboard.filelibrary')),
            ],
            options={
                'verbose_name': 'إشعار',
                'verbose_name_plural': 'الإشعارات',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CommitteeMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(blank=True, max_length=100, verbose_name='الدور')),
                ('joined_date', models.DateField(auto_now_add=True, verbose_name='تاريخ الانضمام')),
                ('is_active', models.BooleanField(default=True, verbose_name='نشط')),
                ('participation_score', models.IntegerField(default=0, verbose_name='درجة المشاركة')),
                ('committee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cultural_members', to='director_dashboard.committee')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='committee_memberships', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'عضو اللجنة',
                'verbose_name_plural': 'أعضاء اللجنة',
                'unique_together': {('committee', 'user')},
            },
        ),
    ]
