# Generated by Django 5.2.6 on 2025-11-07 21:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cultural_committee_dashboard', '0002_remove_culturaltask_assigned_to_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='culturalnotification',
            name='related_discussion',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='cultural_committee_dashboard.discussion'),
        ),
        migrations.AddField(
            model_name='discussion',
            name='is_public_to_all_supervisors',
            field=models.BooleanField(default=False, verbose_name='مشترك بين جميع المشرفين'),
        ),
    ]
