# Generated by Django 5.2.6 on 2025-11-19 17:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cultural_committee_dashboard', '0003_culturalnotification_related_discussion_and_more'),
        ('director_dashboard', '0003_directoralert_related_discussion'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DailyPhrase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phrase', models.TextField(verbose_name='العبارة')),
                ('author', models.CharField(blank=True, max_length=255, verbose_name='المؤلف (اختياري)')),
                ('category', models.CharField(blank=True, max_length=100, verbose_name='التصنيف (اختياري)')),
                ('is_active', models.BooleanField(default=True, verbose_name='نشط')),
                ('display_date', models.DateField(unique=True, verbose_name='تاريخ العرض')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('committee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='daily_phrases', to='director_dashboard.committee')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'عبارة اليوم',
                'verbose_name_plural': 'عبارات اليوم',
                'ordering': ['-display_date'],
            },
        ),
        migrations.AddField(
            model_name='culturalnotification',
            name='related_daily_phrase',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='cultural_committee_dashboard.dailyphrase'),
        ),
    ]
