# Generated by Django 5.2.6 on 2025-11-29 14:18

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cultural_committee_dashboard', '0004_dailyphrase_and_more'),
        ('director_dashboard', '0003_directoralert_related_discussion'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='culturaltask',
            name='created_by',
        ),
        migrations.AddField(
            model_name='culturaltask',
            name='has_sessions',
            field=models.BooleanField(default=False, verbose_name='يحتوي على جلسات'),
        ),
        migrations.AlterField(
            model_name='culturaltask',
            name='assigned_to_name',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='اسم المسؤول'),
        ),
        migrations.AlterField(
            model_name='culturaltask',
            name='committee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cultural_tasks', to='director_dashboard.committee', verbose_name='اللجنة الثقافية'),
        ),
        migrations.AlterField(
            model_name='culturaltask',
            name='completion_percentage',
            field=models.IntegerField(default=0, help_text='أدخل رقماً بين 0 و 100', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='نسبة الإنجاز'),
        ),
        migrations.AlterField(
            model_name='culturaltask',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء'),
        ),
        migrations.AlterField(
            model_name='culturaltask',
            name='description',
            field=models.TextField(verbose_name='وصف المهمة'),
        ),
        migrations.AlterField(
            model_name='culturaltask',
            name='status',
            field=models.CharField(choices=[('pending', 'قيد الانتظار'), ('in_progress', 'قيد التنفيذ'), ('completed', 'مكتملة'), ('cancelled', 'ملغاة')], default='pending', max_length=20, verbose_name='الحالة'),
        ),
        migrations.AlterField(
            model_name='culturaltask',
            name='task_type',
            field=models.CharField(choices=[('event', 'فعالية ثقافية'), ('workshop', 'ورشة عمل'), ('lecture', 'محاضرة'), ('competition', 'مسابقة'), ('exhibition', 'معرض'), ('activity', 'نشاط'), ('other', 'أخرى')], max_length=20, verbose_name='نوع المهمة'),
        ),
        migrations.AlterField(
            model_name='culturaltask',
            name='title',
            field=models.CharField(max_length=200, verbose_name='عنوان المهمة'),
        ),
        migrations.AlterField(
            model_name='culturaltask',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='تاريخ التحديث'),
        ),
        migrations.CreateModel(
            name='TaskSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='اسم الجلسة')),
                ('date', models.DateField(verbose_name='تاريخ الجلسة')),
                ('time', models.TimeField(verbose_name='وقت الجلسة')),
                ('session_order', models.IntegerField(default=1, verbose_name='ترتيب الجلسة')),
                ('is_completed', models.BooleanField(default=False, verbose_name='مكتملة')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='ملاحظات')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sessions', to='cultural_committee_dashboard.culturaltask', verbose_name='المهمة')),
            ],
            options={
                'verbose_name': 'جلسة',
                'verbose_name_plural': 'الجلسات',
                'ordering': ['date', 'time', 'session_order'],
                'unique_together': {('task', 'session_order')},
            },
        ),
    ]
