# Generated by Django 5.2.6 on 2025-12-11 18:04

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cultural_committee_dashboard', '0005_remove_culturaltask_created_by_and_more'),
        ('director_dashboard', '0004_pointscalculatorsettings_pointsresult'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='dailyphrase',
            options={'ordering': ['day_of_week'], 'verbose_name': 'عبارة اليوم', 'verbose_name_plural': 'عبارات الأسبوع'},
        ),
        migrations.RemoveField(
            model_name='dailyphrase',
            name='display_date',
        ),
        migrations.AddField(
            model_name='dailyphrase',
            name='day_of_week',
            field=models.CharField(choices=[('all', 'جميع الأيام'), ('saturday', 'السبت'), ('sunday', 'الأحد'), ('monday', 'الإثنين'), ('tuesday', 'الثلاثاء'), ('wednesday', 'الأربعاء'), ('thursday', 'الخميس'), ('friday', 'الجمعة')], default='all', max_length=20, verbose_name='يوم الأسبوع'),
        ),
        migrations.AddConstraint(
            model_name='dailyphrase',
            constraint=models.UniqueConstraint(fields=('committee', 'day_of_week'), name='unique_daily_phrase_per_day'),
        ),
    ]
