# Generated by Django 5.2.6 on 2025-12-14 16:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cultural_committee_dashboard', '0006_alter_dailyphrase_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='culturaltask',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_cultural_tasks', to=settings.AUTH_USER_MODEL, verbose_name='تم الإنشاء بواسطة'),
        ),
        migrations.AddField(
            model_name='culturaltask',
            name='is_recurring',
            field=models.BooleanField(default=False, verbose_name='مهمة متكررة'),
        ),
        migrations.AddField(
            model_name='culturaltask',
            name='priority',
            field=models.CharField(choices=[('low', 'منخفضة'), ('medium', 'متوسطة'), ('high', 'عالية')], default='medium', max_length=20, verbose_name='الأولوية'),
        ),
        migrations.AddField(
            model_name='culturaltask',
            name='recurrence_days',
            field=models.JSONField(blank=True, null=True, verbose_name='أيام التكرار'),
        ),
        migrations.AddField(
            model_name='culturaltask',
            name='recurrence_end_date',
            field=models.DateField(blank=True, null=True, verbose_name='تاريخ انتهاء التكرار'),
        ),
        migrations.AddField(
            model_name='culturaltask',
            name='recurrence_pattern',
            field=models.CharField(blank=True, choices=[('daily', 'يومي'), ('weekly', 'أسبوعي'), ('custom', 'مخصص')], max_length=20, null=True, verbose_name='نمط التكرار'),
        ),
        migrations.AddField(
            model_name='culturaltask',
            name='start_date',
            field=models.DateField(blank=True, null=True, verbose_name='تاريخ البداية'),
        ),
    ]
