# Generated by Django 5.2.6 on 2025-10-13 13:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('director_dashboard', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DirectorAlbum',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='عنوان الألبوم')),
                ('description', models.TextField(blank=True, verbose_name='الوصف')),
                ('cover_image', models.ImageField(upload_to='albums/covers/%Y/%m/', verbose_name='صورة الغلاف')),
                ('is_active', models.BooleanField(default=True, verbose_name='نشط')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'ألبوم',
                'verbose_name_plural': 'الألبومات',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='AlbumPhoto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='عنوان الصورة')),
                ('image', models.ImageField(upload_to='albums/photos/%Y/%m/', verbose_name='الصورة')),
                ('description', models.TextField(blank=True, verbose_name='الوصف')),
                ('order', models.IntegerField(default=0, verbose_name='ترتيب')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('album', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='director_dashboard.directoralbum')),
            ],
            options={
                'verbose_name': 'صورة',
                'verbose_name_plural': 'الصور',
                'ordering': ['order', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='DirectorAlert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='العنوان')),
                ('message', models.TextField(verbose_name='الرسالة')),
                ('alert_type', models.CharField(choices=[('supervisor_added', 'إضافة مشرف لجنة'), ('task_added', 'إضافة مهمة'), ('program_created', 'إنشاء برنامج'), ('committee_created', 'إنشاء لجنة'), ('report_submitted', 'تسليم تقرير'), ('system_alert', 'تنبيه نظام')], max_length=50, verbose_name='نوع التنبيه')),
                ('priority', models.CharField(choices=[('low', 'منخفض'), ('medium', 'متوسط'), ('high', 'عالي')], default='medium', max_length=20, verbose_name='الأولوية')),
                ('is_read', models.BooleanField(default=False, verbose_name='مقروء')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('action_url', models.CharField(blank=True, max_length=500, verbose_name='رابط الإجراء')),
                ('related_committee', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='director_dashboard.committee', verbose_name='اللجنة المرتبطة')),
                ('related_program', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='director_dashboard.program', verbose_name='البرنامج المرتبط')),
                ('related_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='caused_alerts', to=settings.AUTH_USER_MODEL, verbose_name='المستخدم المرتبط')),
            ],
            options={
                'verbose_name': 'تنبيه',
                'verbose_name_plural': 'التنبيهات',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='DirectorFileLibrary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='العنوان')),
                ('description', models.TextField(blank=True, verbose_name='الوصف')),
                ('file_type', models.CharField(choices=[('video', 'فيديو'), ('presentation', 'عرض تقديمي'), ('document', 'وثيقة'), ('image', 'صورة'), ('audio', 'ملف صوتي'), ('other', 'أخرى')], max_length=50, verbose_name='نوع الملف')),
                ('file', models.FileField(upload_to='director_files/%Y/%m/', verbose_name='الملف')),
                ('thumbnail', models.ImageField(blank=True, null=True, upload_to='file_thumbnails/%Y/%m/', verbose_name='صورة مصغرة')),
                ('is_public', models.BooleanField(default=True, verbose_name='عام')),
                ('download_count', models.IntegerField(default=0, verbose_name='عدد التحميلات')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('uploaded_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'ملف',
                'verbose_name_plural': 'مكتبة الملفات',
                'ordering': ['-uploaded_at'],
            },
        ),
    ]
