# Generated by Django 5.2.6 on 2025-11-07 21:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cultural_committee_dashboard', '0003_culturalnotification_related_discussion_and_more'),
        ('director_dashboard', '0002_directoralbum_albumphoto_directoralert_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='directoralert',
            name='related_discussion',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='cultural_committee_dashboard.discussion'),
        ),
    ]
