# Generated by Django 5.2.6 on 2025-12-11 12:27

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('director_dashboard', '0003_directoralert_related_discussion'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PointsCalculatorSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('program_name', models.CharField(default='عشائر آل سلطان', max_length=200, verbose_name='اسم البرنامج')),
                ('committees', models.JSONField(default=list, help_text="قائمة بأسماء اللجان، مثال: ['الثقافية', 'الإعلامية', 'العلمية']", verbose_name='اللجان')),
                ('batches', models.JSONField(default=list, help_text="قائمة بالدفعات، مثال: [{'name': 'ثالث', 'student_count': 8, 'emoji': '🎯', 'students': ['اسم1', 'اسم2']}, ...]", verbose_name='الدفعات')),
                ('current_week', models.IntegerField(default=1, help_text='رقم الأسبوع الذي سيظهر في القالب', verbose_name='رقم الأسبوع الحالي')),
                ('default_committee_name', models.CharField(default='[يكتب هنا اسم اللجنة]', max_length=200, verbose_name='النص الافتراضي لاسم اللجنة')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='points_settings', to=settings.AUTH_USER_MODEL, verbose_name='المستخدم')),
            ],
            options={
                'verbose_name': 'إعدادات حاسبة النقاط',
                'verbose_name_plural': 'إعدادات حاسبة النقاط',
            },
        ),
        migrations.CreateModel(
            name='PointsResult',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('summary_data', models.JSONField(default=dict, verbose_name='بيانات الملخص')),
                ('week_number', models.IntegerField(blank=True, null=True, verbose_name='رقم الأسبوع')),
                ('program_name', models.CharField(default='عشائر آل سلطان', max_length=200, verbose_name='اسم البرنامج')),
                ('share_url', models.CharField(max_length=200, unique=True, verbose_name='رابط المشاركة')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField(blank=True, null=True, verbose_name='تاريخ انتهاء الصلاحية')),
                ('student_images', models.JSONField(blank=True, default=dict, help_text="قاموس يحفظ صور الطلاب: {'اسم الطالب': 'رابط الصورة'}", verbose_name='صور الطلاب')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='points_results', to=settings.AUTH_USER_MODEL, verbose_name='المستخدم')),
            ],
            options={
                'verbose_name': 'نتيجة حساب النقاط',
                'verbose_name_plural': 'نتائج حساب النقاط',
                'ordering': ['-created_at'],
            },
        ),
    ]
