# Generated by Django 5.2.6 on 2025-12-12 12:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Takwin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('aspect', models.CharField(choices=[('tarbawiu', 'تربوي'), ('shareiu', 'شرعي'), ('mhari', 'مهاري'), ('medad', 'مداد')], max_length=20, verbose_name='الجانب')),
                ('title', models.CharField(max_length=200, verbose_name='عنوان التكوين')),
                ('description', models.TextField(verbose_name='وصف التكوين')),
                ('image', models.ImageField(blank=True, null=True, upload_to='takwin_images/', verbose_name='صورة')),
                ('link', models.URLField(blank=True, null=True, verbose_name='رابط')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('pdf', models.FileField(blank=True, null=True, upload_to='pdfs/', verbose_name='ملف pdf')),
            ],
            options={
                'verbose_name': 'تكوين',
                'verbose_name_plural': 'التكوين',
            },
        ),
        migrations.CreateModel(
            name='UserTakwin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_done', models.BooleanField(default=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('takwin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_takwins', to='takwin.takwin')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_takwins', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'تكوين المستخدم',
                'verbose_name_plural': 'تكوين المستخدمين',
            },
        ),
    ]
