# Generated by Django 5.2.6 on 2025-10-02 10:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        ('director_dashboard', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProgramSupervisor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_supervisors', to=settings.AUTH_USER_MODEL)),
                ('program', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='director_dashboard.program')),
                ('supervisor', models.ForeignKey(limit_choices_to={'role': 'committee_supervisor'}, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'مشرف برنامج',
                'verbose_name_plural': 'مشرفي البرامج',
                'unique_together': {('program', 'supervisor')},
            },
        ),
    ]
