# Generated by Django 5.2.6 on 2025-10-05 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_passwordresettoken'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='supervisor_type',
            field=models.CharField(blank=True, choices=[('cultural', 'مشرف لجنة ثقافية'), ('sports', 'مشرف لجنة رياضية'), ('', 'غير محدد')], max_length=20, verbose_name='نوع المشرف'),
        ),
    ]
