# Generated by Django 5.2.6 on 2025-10-08 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_user_supervisor_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='supervisor_type',
            field=models.CharField(blank=True, choices=[('cultural', 'مشرف لجنة ثقافية'), ('sports', 'مشرف لجنة رياضية'), ('sharia', 'مشرف اللجنة الشرعية'), ('', 'غير محدد')], max_length=20, verbose_name='نوع المشرف'),
        ),
    ]
