# Generated by Django 5.2.6 on 2025-10-20 22:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_alter_user_supervisor_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='supervisor_type',
            field=models.CharField(blank=True, choices=[('cultural', 'مشرف لجنة ثقافية'), ('sports', 'مشرف لجنة رياضية'), ('sharia', 'مشرف اللجنة الشرعية'), ('scientific', 'مشرف اللجنة العلمية'), ('operations', 'مشرف اللجنة التشغيلية'), ('', 'غير محدد')], max_length=20, verbose_name='نوع المشرف'),
        ),
    ]
