# Generated by Django 5.2.6 on 2025-11-07 15:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pm_dashboard', '0001_initial'),
        ('sports_committee_dashboard', '0006_sportstask_from_program_manager_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='is_sports_task',
            field=models.BooleanField(default=False, verbose_name='مهمة رياضية'),
        ),
        migrations.AddField(
            model_name='task',
            name='sports_task_ref',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='sports_committee_dashboard.sportstask', verbose_name='المهمة الرياضية المرجعية'),
        ),
    ]
