# Generated by Django 5.2.6 on 2025-11-07 15:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pm_dashboard', '0002_task_is_sports_task_task_sports_task_ref'),
        ('scientific_committee_dashboard', '0001_initial'),
        ('sharia_committee_dashboard', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='is_scientific_task',
            field=models.BooleanField(default=False, verbose_name='مهمة علمية'),
        ),
        migrations.AddField(
            model_name='task',
            name='is_sharia_task',
            field=models.BooleanField(default=False, verbose_name='مهمة شرعية'),
        ),
        migrations.AddField(
            model_name='task',
            name='scientific_task_ref',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='scientific_committee_dashboard.scientifictask', verbose_name='المهمة العلمية المرجعية'),
        ),
        migrations.AddField(
            model_name='task',
            name='sharia_task_ref',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='sharia_committee_dashboard.shariatask', verbose_name='المهمة الشرعية المرجعية'),
        ),
    ]
