# Generated by Django 5.2.6 on 2025-11-07 15:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cultural_committee_dashboard', '0001_initial'),
        ('pm_dashboard', '0003_task_is_scientific_task_task_is_sharia_task_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='cultural_task_ref',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='cultural_committee_dashboard.culturaltask', verbose_name='المهمة الثقافية المرجعية'),
        ),
        migrations.AddField(
            model_name='task',
            name='is_cultural_task',
            field=models.BooleanField(default=False, verbose_name='مهمة ثقافية'),
        ),
    ]
