# Generated by Django 5.2.6 on 2025-11-07 15:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operations_committee_dashboard', '0001_initial'),
        ('pm_dashboard', '0004_task_cultural_task_ref_task_is_cultural_task'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='is_operations_task',
            field=models.BooleanField(default=False, verbose_name='مهمة تشغيلية'),
        ),
        migrations.AddField(
            model_name='task',
            name='operations_task_ref',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='operations_committee_dashboard.operationstask', verbose_name='المهمة التشغيلية المرجعية'),
        ),
    ]
