# Generated by Django 5.2.6 on 2025-11-07 21:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cultural_committee_dashboard', '0003_culturalnotification_related_discussion_and_more'),
        ('pm_dashboard', '0005_task_is_operations_task_task_operations_task_ref'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='related_discussion',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='cultural_committee_dashboard.discussion'),
        ),
    ]
