# Generated by Django 5.2.6 on 2025-11-07 21:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pm_dashboard', '0006_notification_related_discussion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='notification_type',
            field=models.CharField(choices=[('task_added', 'مهمة جديدة'), ('committee_delayed', 'تأخر لجنة'), ('task_overdue', 'مهمة متأخرة'), ('activity_reminder', 'تذكير بنشاط'), ('discussion_created', 'نقاش جديد')], max_length=50),
        ),
    ]
