# Generated by Django 5.2.6 on 2025-12-12 21:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pm_dashboard', '0007_alter_notification_notification_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='is_recurring',
            field=models.BooleanField(default=False, verbose_name='مهمة متكررة'),
        ),
        migrations.AddField(
            model_name='task',
            name='recurrence_days',
            field=models.JSONField(blank=True, null=True, verbose_name='أيام التكرار'),
        ),
        migrations.AddField(
            model_name='task',
            name='recurrence_end_date',
            field=models.DateField(blank=True, null=True, verbose_name='تاريخ انتهاء التكرار'),
        ),
        migrations.AddField(
            model_name='task',
            name='recurrence_pattern',
            field=models.CharField(blank=True, choices=[('daily', 'يومي'), ('weekly', 'أسبوعي'), ('custom', 'مخصص')], max_length=20, null=True, verbose_name='نمط التكرار'),
        ),
        migrations.AddField(
            model_name='task',
            name='start_date',
            field=models.DateField(blank=True, null=True, verbose_name='تاريخ البداية'),
        ),
    ]
