# Generated by Django 5.2.6 on 2025-10-06 20:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('director_dashboard', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Match',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('match_type', models.CharField(choices=[('football', 'كرة قدم'), ('volleyball', 'كرة طائرة'), ('table_tennis', 'تنس طاولة'), ('playstation', 'بلايستيشن'), ('intelligence_game', 'لعبة ذكاء'), ('other', 'أخرى')], max_length=50, verbose_name='نوع المباراة')),
                ('title', models.CharField(max_length=255, verbose_name='العنوان')),
                ('team1', models.CharField(max_length=100, verbose_name='الفريق الأول')),
                ('team2', models.CharField(max_length=100, verbose_name='الفريق الثاني')),
                ('date', models.DateField(verbose_name='التاريخ')),
                ('time', models.TimeField(verbose_name='الوقت')),
                ('location', models.CharField(max_length=255, verbose_name='المكان')),
                ('status', models.CharField(choices=[('scheduled', 'مجدولة'), ('ongoing', 'جارية'), ('completed', 'مكتملة'), ('cancelled', 'ملغاة')], default='scheduled', max_length=20, verbose_name='الحالة')),
                ('team1_score', models.IntegerField(blank=True, null=True, verbose_name='نتيجة الفريق الأول')),
                ('team2_score', models.IntegerField(blank=True, null=True, verbose_name='نتيجة الفريق الثاني')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('committee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='matches', to='director_dashboard.committee')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('referee', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='refereed_matches', to=settings.AUTH_USER_MODEL, verbose_name='الحكم')),
            ],
            options={
                'verbose_name': 'مباراة',
                'verbose_name_plural': 'المباريات',
                'ordering': ['-date', '-time'],
            },
        ),
        migrations.CreateModel(
            name='SportsFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_type', models.CharField(choices=[('match_schedule', 'جدول مباريات'), ('results', 'نتائج'), ('activity_photos', 'صور الأنشطة'), ('other', 'أخرى')], max_length=50, verbose_name='نوع الملف')),
                ('title', models.CharField(max_length=255, verbose_name='العنوان')),
                ('description', models.TextField(blank=True, verbose_name='الوصف')),
                ('file', models.FileField(upload_to='sports_files/%Y/%m/', verbose_name='الملف')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('committee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sports_files', to='director_dashboard.committee')),
                ('uploaded_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'ملف رياضي',
                'verbose_name_plural': 'مكتبة الملفات الرياضية',
                'ordering': ['-uploaded_at'],
            },
        ),
        migrations.CreateModel(
            name='SportsReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='عنوان التقرير')),
                ('week_start', models.DateField(verbose_name='بداية الأسبوع')),
                ('week_end', models.DateField(verbose_name='نهاية الأسبوع')),
                ('content', models.TextField(verbose_name='المحتوى')),
                ('participation_rate', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='نسبة المشاركة')),
                ('file', models.FileField(blank=True, null=True, upload_to='sports_reports/%Y/%m/', verbose_name='ملف مرفق')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('committee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sports_reports', to='director_dashboard.committee')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'تقرير رياضي',
                'verbose_name_plural': 'التقارير الرياضية',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SportsTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task_type', models.CharField(choices=[('football_volleyball', 'دوري القدم والطائرة'), ('sports_programs', 'البرامج الرياضية والمسابقات الحركية'), ('hall_meetings', 'متابعة لقاءات الصالة'), ('table_tennis', 'دوري تنس الطاولة'), ('playstation', 'دوري البلايستيشن'), ('intelligence_games', 'متابعة ألعاب الذكاء')], max_length=50, verbose_name='نوع المهمة')),
                ('title', models.CharField(max_length=255, verbose_name='العنوان')),
                ('description', models.TextField(verbose_name='الوصف')),
                ('status', models.CharField(choices=[('pending', 'قيد التنفيذ'), ('in_progress', 'جاري العمل'), ('completed', 'مكتملة'), ('cancelled', 'ملغاة')], default='pending', max_length=20, verbose_name='الحالة')),
                ('due_date', models.DateField(verbose_name='تاريخ الاستحقاق')),
                ('completion_percentage', models.IntegerField(default=0, verbose_name='نسبة الإنجاز')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assigned_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sports_tasks_assigned', to=settings.AUTH_USER_MODEL, verbose_name='المسؤول')),
                ('committee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sports_tasks', to='director_dashboard.committee')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sports_tasks_created', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'مهمة رياضية',
                'verbose_name_plural': 'المهام الرياضية',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SportsNotification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notification_type', models.CharField(choices=[('match_scheduled', 'مباراة مجدولة'), ('results_uploaded', 'رفع النتائج'), ('task_added', 'إضافة مهمة'), ('task_updated', 'تعديل مهمة'), ('report_uploaded', 'رفع تقرير')], max_length=50)),
                ('title', models.CharField(max_length=255)),
                ('message', models.TextField()),
                ('is_read', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('committee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sports_notifications', to='director_dashboard.committee')),
                ('related_match', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='sports_committee_dashboard.match')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sports_notifications', to=settings.AUTH_USER_MODEL)),
                ('related_report', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='sports_committee_dashboard.sportsreport')),
                ('related_task', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='sports_committee_dashboard.sportstask')),
            ],
            options={
                'verbose_name': 'إشعار رياضي',
                'verbose_name_plural': 'الإشعارات الرياضية',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SportsMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('referee', 'حكم'), ('coordinator', 'منسق'), ('responsible_player', 'لاعب مسؤول'), ('player', 'لاعب')], max_length=50, verbose_name='الدور')),
                ('joined_date', models.DateField(auto_now_add=True, verbose_name='تاريخ الانضمام')),
                ('is_active', models.BooleanField(default=True, verbose_name='نشط')),
                ('participation_score', models.IntegerField(default=0, verbose_name='درجة المشاركة')),
                ('committee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sports_members', to='director_dashboard.committee')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sports_memberships', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'عضو اللجنة الرياضية',
                'verbose_name_plural': 'أعضاء اللجنة الرياضية',
                'unique_together': {('committee', 'user')},
            },
        ),
    ]
