# Generated by Django 5.2.6 on 2025-11-07 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sports_committee_dashboard', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sportstask',
            name='assigned_to',
        ),
        migrations.AddField(
            model_name='sportstask',
            name='assigned_to_name',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='اسم المسؤول'),
        ),
    ]
