# Generated by Django 5.2.6 on 2025-11-07 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sports_committee_dashboard', '0002_remove_sportstask_assigned_to_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='match',
            name='referee',
        ),
        migrations.AddField(
            model_name='match',
            name='referee_name',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='اسم الحكم'),
        ),
    ]
