# Generated by Django 5.2.6 on 2025-11-07 14:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
        ('sports_committee_dashboard', '0003_remove_match_referee_match_referee_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='sportstask',
            name='director_event',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.scheduleevent', verbose_name='الحدث المرتبط'),
        ),
        migrations.AddField(
            model_name='sportstask',
            name='from_director_event',
            field=models.BooleanField(default=False, verbose_name='من حدث المدير'),
        ),
    ]
