# Generated by Django 5.2.6 on 2025-11-07 15:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sports_committee_dashboard', '0004_sportstask_director_event_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sportstask',
            name='director_event',
        ),
        migrations.RemoveField(
            model_name='sportstask',
            name='from_director_event',
        ),
    ]
