# Generated by Django 5.2.6 on 2025-11-07 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sports_committee_dashboard', '0005_remove_sportstask_director_event_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sportstask',
            name='from_program_manager',
            field=models.BooleanField(default=False, verbose_name='من مدير البرنامج'),
        ),
        migrations.AlterField(
            model_name='sportstask',
            name='task_type',
            field=models.CharField(choices=[('football_volleyball', 'دوري القدم والطائرة'), ('sports_programs', 'البرامج الرياضية والمسابقات الحركية'), ('hall_meetings', 'متابعة لقاءات الصالة'), ('table_tennis', 'دوري تنس الطاولة'), ('playstation', 'دوري البلايستيشن'), ('intelligence_games', 'متابعة ألعاب الذكاء'), ('other', 'أخرى')], max_length=50, verbose_name='نوع المهمة'),
        ),
    ]
