# Generated by Django 5.2.6 on 2025-11-07 21:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sports_committee_dashboard', '0007_sportsnotification_related_discussion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sportsnotification',
            name='notification_type',
            field=models.CharField(choices=[('match_scheduled', 'مباراة مجدولة'), ('results_uploaded', 'رفع النتائج'), ('task_added', 'إضافة مهمة'), ('task_updated', 'تعديل مهمة'), ('report_uploaded', 'رفع تقرير'), ('discussion_created', 'نقاش جديد')], max_length=50),
        ),
    ]
