# Generated by Django 5.2.6 on 2025-10-13 11:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('director_dashboard', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Lecture',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lecture_type', models.CharField(choices=[('lecture', 'محاضرة'), ('workshop', 'ورشة عمل'), ('seminar', 'ندوة'), ('hosting', 'استضافة')], max_length=20, verbose_name='نوع المحاضرة')),
                ('title', models.CharField(max_length=255, verbose_name='العنوان')),
                ('description', models.TextField(verbose_name='الوصف')),
                ('guest_lecturer', models.CharField(blank=True, max_length=255, verbose_name='محاضر ضيف')),
                ('date', models.DateField(verbose_name='التاريخ')),
                ('time', models.TimeField(verbose_name='الوقت')),
                ('location', models.CharField(max_length=255, verbose_name='المكان')),
                ('duration_minutes', models.IntegerField(verbose_name='المدة (بالدقائق)')),
                ('status', models.CharField(choices=[('scheduled', 'مجدولة'), ('ongoing', 'جارية'), ('completed', 'مكتملة'), ('cancelled', 'ملغاة')], default='scheduled', max_length=20, verbose_name='الحالة')),
                ('attendance_count', models.IntegerField(default=0, verbose_name='عدد الحضور')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('committee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lectures', to='director_dashboard.committee')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lectures_created', to=settings.AUTH_USER_MODEL)),
                ('lecturer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lectures_given', to=settings.AUTH_USER_MODEL, verbose_name='المحاضر')),
            ],
            options={
                'verbose_name': 'محاضرة',
                'verbose_name_plural': 'المحاضرات والورش',
                'ordering': ['-date', '-time'],
            },
        ),
        migrations.CreateModel(
            name='ScientificFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_type', models.CharField(choices=[('research_paper', 'ورقة علمية'), ('presentation', 'عرض تقديمي'), ('lecture_notes', 'ملاحظات محاضرة'), ('workshop_material', 'مواد ورشة عمل'), ('other', 'أخرى')], max_length=50, verbose_name='نوع الملف')),
                ('title', models.CharField(max_length=255, verbose_name='العنوان')),
                ('description', models.TextField(blank=True, verbose_name='الوصف')),
                ('author', models.CharField(blank=True, max_length=255, verbose_name='المؤلف')),
                ('file', models.FileField(upload_to='scientific_files/%Y/%m/', verbose_name='الملف')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('committee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scientific_files', to='director_dashboard.committee')),
                ('uploaded_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'ملف علمي',
                'verbose_name_plural': 'مكتبة الملفات العلمية',
                'ordering': ['-uploaded_at'],
            },
        ),
        migrations.CreateModel(
            name='ScientificReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('report_type', models.CharField(choices=[('attendance', 'تقرير حضور'), ('hosting_evaluation', 'تقييم الاستضافات'), ('monthly', 'تقرير شهري'), ('activity_summary', 'ملخص الأنشطة')], max_length=50, verbose_name='نوع التقرير')),
                ('title', models.CharField(max_length=255, verbose_name='عنوان التقرير')),
                ('content', models.TextField(verbose_name='المحتوى')),
                ('attendance_rate', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='نسبة الحضور')),
                ('evaluation_score', models.DecimalField(blank=True, decimal_places=1, max_digits=3, null=True, verbose_name='درجة التقييم')),
                ('file', models.FileField(blank=True, null=True, upload_to='scientific_reports/%Y/%m/', verbose_name='ملف مرفق')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('committee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scientific_reports', to='director_dashboard.committee')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'تقرير علمي',
                'verbose_name_plural': 'التقارير العلمية',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ScientificTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task_type', models.CharField(choices=[('supervisor_lessons', 'دروس مشرفين'), ('hosting_coordination', 'تنسيق الاستضافات'), ('lessons_officer', 'مسؤول الدروس'), ('adhan_officer', 'مسؤول الأذان'), ('shoulders_adhan_prayer', 'الكتافات والأذان والصلاة'), ('scientific_data', 'بيانات علمية (ضربات)')], max_length=50, verbose_name='نوع المهمة')),
                ('title', models.CharField(max_length=255, verbose_name='العنوان')),
                ('description', models.TextField(verbose_name='الوصف')),
                ('status', models.CharField(choices=[('pending', 'قيد التنفيذ'), ('in_progress', 'جاري العمل'), ('completed', 'مكتملة'), ('cancelled', 'ملغاة')], default='pending', max_length=20, verbose_name='الحالة')),
                ('due_date', models.DateField(verbose_name='تاريخ الاستحقاق')),
                ('completion_percentage', models.IntegerField(default=0, verbose_name='نسبة الإنجاز')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assigned_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='scientific_tasks_assigned', to=settings.AUTH_USER_MODEL, verbose_name='المسؤول')),
                ('committee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scientific_tasks', to='director_dashboard.committee')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='scientific_tasks_created', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'مهمة علمية',
                'verbose_name_plural': 'المهام العلمية',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ScientificNotification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notification_type', models.CharField(choices=[('task_added', 'إضافة مهمة'), ('task_updated', 'تعديل مهمة'), ('lecture_scheduled', 'محاضرة مجدولة'), ('workshop_added', 'إضافة ورشة عمل'), ('file_uploaded', 'رفع ملف'), ('report_uploaded', 'رفع تقرير')], max_length=50)),
                ('title', models.CharField(max_length=255)),
                ('message', models.TextField()),
                ('is_read', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('committee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scientific_notifications', to='director_dashboard.committee')),
                ('related_file', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='scientific_committee_dashboard.scientificfile')),
                ('related_lecture', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='scientific_committee_dashboard.lecture')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scientific_notifications', to=settings.AUTH_USER_MODEL)),
                ('related_report', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='scientific_committee_dashboard.scientificreport')),
                ('related_task', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='scientific_committee_dashboard.scientifictask')),
            ],
            options={
                'verbose_name': 'إشعار علمي',
                'verbose_name_plural': 'الإشعارات العلمية',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='LectureAttendance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attended', models.BooleanField(default=False, verbose_name='حضر')),
                ('notes', models.TextField(blank=True, verbose_name='ملاحظات')),
                ('rating', models.IntegerField(blank=True, null=True, verbose_name='التقييم')),
                ('recorded_at', models.DateTimeField(auto_now_add=True)),
                ('lecture', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendances', to='scientific_committee_dashboard.lecture')),
                ('recorded_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='recorded_lecture_attendances', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lecture_attendances', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'حضور محاضرة',
                'verbose_name_plural': 'حضور المحاضرات',
                'unique_together': {('lecture', 'user')},
            },
        ),
        migrations.CreateModel(
            name='ScientificMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('lecturer', 'محاضر'), ('coordinator', 'منسق'), ('researcher', 'باحث')], max_length=50, verbose_name='الدور')),
                ('joined_date', models.DateField(auto_now_add=True, verbose_name='تاريخ الانضمام')),
                ('is_active', models.BooleanField(default=True, verbose_name='نشط')),
                ('participation_score', models.IntegerField(default=0, verbose_name='درجة المشاركة')),
                ('specialization', models.CharField(blank=True, max_length=255, verbose_name='التخصص')),
                ('committee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scientific_members', to='director_dashboard.committee')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scientific_memberships', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'عضو اللجنة العلمية',
                'verbose_name_plural': 'أعضاء اللجنة العلمية',
                'unique_together': {('committee', 'user')},
            },
        ),
    ]
