# Generated by Django 5.2.6 on 2025-11-07 21:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scientific_committee_dashboard', '0003_scientificnotification_related_discussion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scientificnotification',
            name='notification_type',
            field=models.CharField(choices=[('task_added', 'إضافة مهمة'), ('task_updated', 'تعديل مهمة'), ('lecture_scheduled', 'محاضرة مجدولة'), ('workshop_added', 'إضافة ورشة عمل'), ('file_uploaded', 'رفع ملف'), ('report_uploaded', 'رفع تقرير'), ('discussion_created', 'نقاش جديد')], max_length=50),
        ),
    ]
