# Generated by Django 5.2.6 on 2025-12-15 00:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scientific_committee_dashboard', '0004_alter_scientificnotification_notification_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='scientifictask',
            name='is_recurring',
            field=models.BooleanField(default=False, verbose_name='مهمة متكررة'),
        ),
        migrations.AddField(
            model_name='scientifictask',
            name='recurrence_days',
            field=models.JSONField(blank=True, null=True, verbose_name='أيام التكرار'),
        ),
        migrations.AddField(
            model_name='scientifictask',
            name='recurrence_end_date',
            field=models.DateField(blank=True, null=True, verbose_name='تاريخ انتهاء التكرار'),
        ),
        migrations.AddField(
            model_name='scientifictask',
            name='recurrence_pattern',
            field=models.CharField(blank=True, choices=[('daily', 'يومي'), ('weekly', 'أسبوعي'), ('custom', 'مخصص')], max_length=20, null=True, verbose_name='نمط التكرار'),
        ),
        migrations.AddField(
            model_name='scientifictask',
            name='start_date',
            field=models.DateField(blank=True, null=True, verbose_name='تاريخ البداية'),
        ),
    ]
