# Generated by Django 5.2.6 on 2025-10-20 22:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('director_dashboard', '0002_directoralbum_albumphoto_directoralert_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LogisticsResource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('resource_type', models.CharField(choices=[('equipment', 'معدات'), ('venue', 'مكان'), ('transport', 'مواصلات'), ('materials', 'مواد'), ('budget', 'ميزانية'), ('other', 'أخرى')], max_length=50, verbose_name='نوع المورد')),
                ('name', models.CharField(max_length=255, verbose_name='الاسم')),
                ('description', models.TextField(blank=True, verbose_name='الوصف')),
                ('quantity', models.IntegerField(default=1, verbose_name='الكمية')),
                ('status', models.CharField(choices=[('available', 'متوفر'), ('reserved', 'محجوز'), ('in_use', 'قيد الاستخدام'), ('maintenance', 'صيانة'), ('unavailable', 'غير متوفر')], default='available', max_length=20, verbose_name='الحالة')),
                ('location', models.CharField(blank=True, max_length=255, verbose_name='الموقع')),
                ('notes', models.TextField(blank=True, verbose_name='ملاحظات')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('committee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logistics_resources', to='director_dashboard.committee')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'مورد لوجستي',
                'verbose_name_plural': 'الموارد اللوجستية',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='OperationsFileLibrary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_type', models.CharField(choices=[('operational_plan', 'خطة تشغيلية'), ('preparation_list', 'قائمة تجهيز'), ('schedule', 'جدول زمني'), ('report', 'تقرير'), ('other', 'أخرى')], max_length=50, verbose_name='نوع الملف')),
                ('title', models.CharField(max_length=255, verbose_name='العنوان')),
                ('description', models.TextField(blank=True, verbose_name='الوصف')),
                ('file', models.FileField(upload_to='operations_files/%Y/%m/', verbose_name='الملف')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('committee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='operations_files', to='director_dashboard.committee')),
                ('uploaded_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'ملف تشغيلي',
                'verbose_name_plural': 'مكتبة الملفات',
                'ordering': ['-uploaded_at'],
            },
        ),
        migrations.CreateModel(
            name='OperationsTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task_type', models.CharField(choices=[('operational_program', 'البرنامج التشغيلي'), ('awards_provision', 'توفير الجوائز'), ('individuals_families_followup', 'متابعة الأفراد والأسر'), ('public_program', 'البرنامج الجماهيري'), ('visits_coordination', 'معاون تنسيق الزيارات')], max_length=50, verbose_name='نوع المهمة')),
                ('title', models.CharField(max_length=255, verbose_name='العنوان')),
                ('description', models.TextField(verbose_name='الوصف')),
                ('status', models.CharField(choices=[('not_started', 'لم يبدأ'), ('in_progress', 'جاري'), ('completed', 'مكتمل'), ('overdue', 'متأخر')], default='not_started', max_length=20, verbose_name='الحالة')),
                ('priority', models.CharField(choices=[('low', 'منخفضة'), ('medium', 'متوسطة'), ('high', 'عالية')], default='medium', max_length=20, verbose_name='الأولوية')),
                ('due_date', models.DateField(verbose_name='الموعد النهائي')),
                ('completion_percentage', models.IntegerField(default=0, verbose_name='نسبة الإنجاز')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assigned_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='operations_tasks_assigned', to=settings.AUTH_USER_MODEL, verbose_name='مسؤول الفريق')),
                ('committee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='operations_tasks', to='director_dashboard.committee')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='operations_tasks_created', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'مهمة تشغيلية',
                'verbose_name_plural': 'المهام التشغيلية',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='OperationsNotification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notification_type', models.CharField(choices=[('task_added', 'إضافة مهمة'), ('task_updated', 'تعديل مهمة'), ('task_overdue', 'مهمة متأخرة'), ('resource_added', 'إضافة مورد'), ('report_uploaded', 'رفع تقرير')], max_length=50)),
                ('title', models.CharField(max_length=255)),
                ('message', models.TextField()),
                ('is_read', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('committee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='operations_notifications', to='director_dashboard.committee')),
                ('related_resource', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='operations_committee_dashboard.logisticsresource')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='operations_notifications', to=settings.AUTH_USER_MODEL)),
                ('related_task', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='operations_committee_dashboard.operationstask')),
            ],
            options={
                'verbose_name': 'إشعار',
                'verbose_name_plural': 'الإشعارات',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='OperationsWeeklyReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('week_start_date', models.DateField(verbose_name='بداية الأسبوع')),
                ('week_end_date', models.DateField(verbose_name='نهاية الأسبوع')),
                ('achievements', models.TextField(verbose_name='الإنجازات')),
                ('challenges', models.TextField(verbose_name='التحديات')),
                ('completion_rate', models.IntegerField(default=0, verbose_name='نسبة الإنجاز %')),
                ('tasks_completed', models.IntegerField(default=0, verbose_name='المهام المكتملة')),
                ('tasks_pending', models.IntegerField(default=0, verbose_name='المهام المعلقة')),
                ('notes', models.TextField(blank=True, verbose_name='ملاحظات إضافية')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('committee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='operations_weekly_reports', to='director_dashboard.committee')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'تقرير أسبوعي',
                'verbose_name_plural': 'التقارير الأسبوعية',
                'ordering': ['-week_start_date'],
            },
        ),
        migrations.CreateModel(
            name='OperationsTeamMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(blank=True, max_length=100, verbose_name='الدور')),
                ('joined_date', models.DateField(auto_now_add=True, verbose_name='تاريخ الانضمام')),
                ('is_active', models.BooleanField(default=True, verbose_name='نشط')),
                ('participation_score', models.IntegerField(default=0, verbose_name='درجة المشاركة')),
                ('committee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='operations_members', to='director_dashboard.committee')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='operations_memberships', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'عضو اللجنة',
                'verbose_name_plural': 'أعضاء اللجنة',
                'unique_together': {('committee', 'user')},
            },
        ),
    ]
