# Generated by Django 5.2.6 on 2025-11-07 21:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operations_committee_dashboard', '0003_operationsnotification_related_discussion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='operationsnotification',
            name='notification_type',
            field=models.CharField(choices=[('task_added', 'إضافة مهمة'), ('task_updated', 'تعديل مهمة'), ('task_overdue', 'مهمة متأخرة'), ('resource_added', 'إضافة مورد'), ('report_uploaded', 'رفع تقرير'), ('discussion_created', 'نقاش جديد')], max_length=50),
        ),
    ]
