# Generated by Django 5.2.6 on 2025-12-16 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operations_committee_dashboard', '0004_alter_operationsnotification_notification_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='operationstask',
            name='is_recurring',
            field=models.BooleanField(default=False, verbose_name='مهمة متكررة'),
        ),
        migrations.AddField(
            model_name='operationstask',
            name='recurrence_days',
            field=models.JSONField(blank=True, null=True, verbose_name='أيام التكرار'),
        ),
        migrations.AddField(
            model_name='operationstask',
            name='recurrence_end_date',
            field=models.DateField(blank=True, null=True, verbose_name='تاريخ انتهاء التكرار'),
        ),
        migrations.AddField(
            model_name='operationstask',
            name='recurrence_pattern',
            field=models.CharField(blank=True, choices=[('daily', 'يومي'), ('weekly', 'أسبوعي'), ('custom', 'مخصص')], max_length=20, null=True, verbose_name='نمط التكرار'),
        ),
        migrations.AddField(
            model_name='operationstask',
            name='start_date',
            field=models.DateField(blank=True, null=True, verbose_name='تاريخ البداية'),
        ),
        migrations.AlterField(
            model_name='operationstask',
            name='task_type',
            field=models.CharField(choices=[('operational_program', 'البرنامج التشغيلي'), ('awards_provision', 'توفير الجوائز'), ('individuals_families_followup', 'متابعة الأفراد والأسر'), ('public_program', 'البرنامج الجماهيري'), ('visits_coordination', 'معاون تنسيق الزيارات'), ('other', 'أخرى')], max_length=50, verbose_name='نوع المهمة'),
        ),
    ]
