# Generated by Django 5.2.6 on 2025-10-08 09:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('director_dashboard', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DailyMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message_type', models.CharField(choices=[('daily', 'يومية'), ('weekly', 'أسبوعية')], max_length=20, verbose_name='نوع الرسالة')),
                ('title', models.CharField(max_length=255, verbose_name='العنوان')),
                ('content', models.TextField(verbose_name='المحتوى')),
                ('scheduled_date', models.DateField(verbose_name='تاريخ الإرسال')),
                ('is_sent', models.BooleanField(default=False, verbose_name='تم الإرسال')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('committee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='daily_messages', to='director_dashboard.committee')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'رسالة',
                'verbose_name_plural': 'الرسائل اليومية والأسبوعية',
                'ordering': ['-scheduled_date'],
            },
        ),
        migrations.CreateModel(
            name='FamilyCompetition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='عنوان المسابقة')),
                ('description', models.TextField(verbose_name='الوصف')),
                ('start_date', models.DateField(verbose_name='تاريخ البداية')),
                ('end_date', models.DateField(verbose_name='تاريخ النهاية')),
                ('status', models.CharField(choices=[('upcoming', 'قادمة'), ('active', 'نشطة'), ('completed', 'مكتملة')], default='upcoming', max_length=20, verbose_name='الحالة')),
                ('file', models.FileField(blank=True, null=True, upload_to='competitions/%Y/%m/', verbose_name='ملف المسابقة')),
                ('participants_count', models.IntegerField(default=0, verbose_name='عدد المشاركين')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('committee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='family_competitions', to='director_dashboard.committee')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'مسابقة أسرية',
                'verbose_name_plural': 'المسابقات الأسرية',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ShariaFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_type', models.CharField(choices=[('lesson', 'درس'), ('article', 'مقال'), ('brochure', 'مطوية'), ('competition', 'مسابقة'), ('book', 'كتاب'), ('other', 'أخرى')], max_length=50, verbose_name='نوع الملف')),
                ('title', models.CharField(max_length=255, verbose_name='العنوان')),
                ('description', models.TextField(blank=True, verbose_name='الوصف')),
                ('file', models.FileField(upload_to='sharia_files/%Y/%m/', verbose_name='الملف')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('committee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sharia_files', to='director_dashboard.committee')),
                ('uploaded_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'ملف شرعي',
                'verbose_name_plural': 'مكتبة الملفات الشرعية',
                'ordering': ['-uploaded_at'],
            },
        ),
        migrations.CreateModel(
            name='ShariaReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='عنوان التقرير')),
                ('report_type', models.CharField(max_length=50, verbose_name='نوع التقرير')),
                ('content', models.TextField(verbose_name='المحتوى')),
                ('interaction_rate', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='نسبة التفاعل')),
                ('file', models.FileField(blank=True, null=True, upload_to='sharia_reports/%Y/%m/', verbose_name='ملف مرفق')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('committee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sharia_reports', to='director_dashboard.committee')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'تقرير شرعي',
                'verbose_name_plural': 'التقارير الشرعية',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ShariaTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task_type', models.CharField(choices=[('honorable_minutes', 'برنامج الدقائق المشرفة'), ('youth_achievement', 'متابعة إنجاز الشباب'), ('daily_message', 'رسالة يومية/أسبوعية'), ('family_competition', 'مسابقة أسرية'), ('weekly_article', 'مقال للقراءة الأسبوعية'), ('youth_books', 'متابعة الكتب الشبابية')], max_length=50, verbose_name='نوع المهمة')),
                ('title', models.CharField(max_length=255, verbose_name='العنوان')),
                ('description', models.TextField(verbose_name='الوصف')),
                ('status', models.CharField(choices=[('pending', 'قيد التنفيذ'), ('in_progress', 'جاري العمل'), ('completed', 'مكتملة'), ('cancelled', 'ملغاة')], default='pending', max_length=20, verbose_name='الحالة')),
                ('due_date', models.DateField(verbose_name='تاريخ الاستحقاق')),
                ('completion_percentage', models.IntegerField(default=0, verbose_name='نسبة الإنجاز')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assigned_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sharia_tasks_assigned', to=settings.AUTH_USER_MODEL, verbose_name='المسؤول')),
                ('committee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sharia_tasks', to='director_dashboard.committee')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sharia_tasks_created', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'مهمة شرعية',
                'verbose_name_plural': 'المهام الشرعية',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ShariaNotification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notification_type', models.CharField(choices=[('task_added', 'إضافة مهمة'), ('task_updated', 'تعديل مهمة'), ('lesson_scheduled', 'موعد درس'), ('competition_uploaded', 'مسابقة جديدة'), ('message_sent', 'إرسال رسالة'), ('report_uploaded', 'رفع تقرير')], max_length=50)),
                ('title', models.CharField(max_length=255)),
                ('message', models.TextField()),
                ('is_read', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('committee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sharia_notifications', to='director_dashboard.committee')),
                ('related_competition', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='sharia_committee_dashboard.familycompetition')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sharia_notifications', to=settings.AUTH_USER_MODEL)),
                ('related_report', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='sharia_committee_dashboard.shariareport')),
                ('related_task', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='sharia_committee_dashboard.shariatask')),
            ],
            options={
                'verbose_name': 'إشعار شرعي',
                'verbose_name_plural': 'الإشعارات الشرعية',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='YouthBook',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='عنوان الكتاب')),
                ('author', models.CharField(max_length=255, verbose_name='المؤلف')),
                ('description', models.TextField(blank=True, verbose_name='الوصف')),
                ('status', models.CharField(choices=[('reading', 'قيد القراءة'), ('completed', 'مكتمل'), ('pending', 'قيد الانتظار')], default='pending', max_length=20, verbose_name='الحالة')),
                ('progress_percentage', models.IntegerField(default=0, verbose_name='نسبة الإنجاز')),
                ('start_date', models.DateField(blank=True, null=True, verbose_name='تاريخ البداية')),
                ('completion_date', models.DateField(blank=True, null=True, verbose_name='تاريخ الإكمال')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('assigned_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_books', to=settings.AUTH_USER_MODEL, verbose_name='مكلف به')),
                ('committee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='youth_books', to='director_dashboard.committee')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_books', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'كتاب شبابي',
                'verbose_name_plural': 'الكتب الشبابية',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ShariaMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(blank=True, max_length=100, verbose_name='الدور')),
                ('joined_date', models.DateField(auto_now_add=True, verbose_name='تاريخ الانضمام')),
                ('is_active', models.BooleanField(default=True, verbose_name='نشط')),
                ('participation_score', models.IntegerField(default=0, verbose_name='درجة المشاركة')),
                ('committee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sharia_members', to='director_dashboard.committee')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sharia_memberships', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'عضو اللجنة الشرعية',
                'verbose_name_plural': 'أعضاء اللجنة الشرعية',
                'unique_together': {('committee', 'user')},
            },
        ),
    ]
