# Generated by Django 5.2.6 on 2025-11-07 21:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sharia_committee_dashboard', '0003_sharianotification_related_discussion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sharianotification',
            name='notification_type',
            field=models.CharField(choices=[('task_added', 'إضافة مهمة'), ('task_updated', 'تعديل مهمة'), ('lesson_scheduled', 'موعد درس'), ('competition_uploaded', 'مسابقة جديدة'), ('message_sent', 'إرسال رسالة'), ('report_uploaded', 'رفع تقرير'), ('discussion_created', 'نقاش جديد')], max_length=50),
        ),
    ]
