# Generated by Django 5.2.6 on 2025-12-16 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sharia_committee_dashboard', '0005_shariatask_is_recurring_shariatask_recurrence_days_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='shariatask',
            name='priority',
            field=models.CharField(choices=[('low', 'منخفضة'), ('medium', 'متوسطة'), ('high', 'عالية')], default='medium', max_length=20, verbose_name='الأولوية'),
        ),
    ]
